Update check platform.

diff --git a/utils/check-environment-compatible b/utils/check-environment-compatible
--- a/utils/check-environment-compatible
+++ b/utils/check-environment-compatible
@@ -1,35 +1,40 @@
 #!/bin/bash
 
 # check docker engine & nvidia-container-runtime
-docker_run=`docker run --rm --gpus all ubuntu`
-retVal=$?
-if [ $retVal -ne 0 ]; then
-    echo "Docker run failed"
-    echo "Environment is not configured properly"
-    exit 1
-fi
+#docker_run=`docker run --rm --gpus all ubuntu`
+#retVal=$?
+#if [ $retVal -ne 0 ]; then
+#    echo "Docker run failed"
+#    echo "Environment is not configured properly"
+#    exit 1
+#fi
 
-linux_ver=`cat /proc/version | cut -d' ' -f 3`
+platform=$(uname -m)
 
-if [[ $linux_ver == *"generic"* ]]; then
+if [[ $platform == "x86_64" ]]; then
     echo "PC platform"
     # check driver version
     driver_version=`nvidia-smi --query-gpu=driver_version --format=csv,noheader --id=0 | cut -d'.' -f 1`
-    if (( $driver_version < 525 )); then
+    if (( driver_version < 525 )); then
         echo "Driver ver >= 525 is required"
         echo "Environment is not configured properly"
         exit 1
     fi
-else
+
+elif [[ $platform == "aarch64" ]]; then
     echo "Jetson platform"
     # check L4T ver
     l4t_ver=`dpkg-query --showformat=\$\{Version\} --show nvidia-l4t-core | cut -d'-' -f 1`
     IFS='.' read -ra l4t_split_ver <<< "$l4t_ver"
-    if (( ${l4t_split_ver[0]} < 35)); then
+    if (( l4t_split_ver[0] < 35)); then
         echo "L4T ver >= 35 is required"
         echo "Environment is not configured properly"
         exit 1
     fi
+
+else
+  echo "Unsupported platform"
+  exit 1
 fi
 
 echo "Environment is OK"
